### ISSUE TITLE
Composer get frozen and unworkable after creating a new sql connector instance

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#1967]
Build: ballerinalang/tools-distribution/org.ballerinalang.tools:ballerina-tools: 378

**Sample code:**
```
function init () (sql:ClientConnector connection){
    string jdbcUrl = system:getEnv("JDBC_URL");
    string jdbcUsername = system:getEnv("JDBC_USERNAME");
    string jdbcPassword = system:getEnv("JDBC_PASSWORD");

    map dbProperties1 = {"jdbcUrl":jdbcUrl, "username":jdbcUsername, "password":jdbcPassword};
    connection = create sql:ClientConnector (dbProperties1);
    return;
}
```
When the  `connection = create sql:ClientConnector (dbProperties1);` is defined through an assignment statement, the composer becomes unusable

![composer_6](https://user-images.githubusercontent.com/15624590/27117208-2b278096-50f3-11e7-81a4-5837965aa7da.png)

After refreshing the `create sql:ClientConnector (dbProperties1)` is set to `b` as given in the below diagram

![composer_7](https://user-images.githubusercontent.com/15624590/27117213-31803442-50f3-11e7-9d8f-14b5c294eaea.png)

**Back end log:** 

```
2017-06-14 11:14:19,541 ERROR - Error while parsing BLang fragment.
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at org.ballerinalang.model.builder.BLangModelBuilder.createAssignmentStmt(BLangModelBuilder.java:1117)
	at org.ballerinalang.util.parser.antlr4.BLangAntlr4Listener.exitAssignmentStatement(BLangAntlr4Listener.java:996)
	at org.ballerinalang.util.parser.BallerinaParser$AssignmentStatementContext.exitRule(BallerinaParser.java:3465)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.ballerinalang.util.parser.BallerinaParser.compilationUnit(BallerinaParser.java:271)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.getJsonModel(BLangFragmentParser.java:118)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:55)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:126)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by hevayo** [comment]
This is no longer reproducible in the latest pack.
