### ISSUE TITLE
Loading-busy icon is shown continuously when trying to expand 'passthroughservice' directory

### ISSUE THREAD

**Issue by lahirus** [ballerinalang/composer#2035]
<img width="976" alt="screen shot 2017-06-18 at 9 11 58 pm" src="https://user-images.githubusercontent.com/3665108/27361520-86376f7e-55ed-11e7-8b1d-5986cf159335.png">
<img width="250" alt="screen shot 2017-06-18 at 9 21 08 pm" src="https://user-images.githubusercontent.com/3665108/27361521-86396a68-55ed-11e7-8c8b-982c33ba9694.png">

**Comment by dakshika** [comment]
017-07-06 17:49:23,070 WARN  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:140)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

**Comment by nadeeshaan** [comment]
This has been fixed in the latest master
