### ISSUE TITLE
Bug when adding sql connector close element to diagram

### ISSUE THREAD

**Issue by upeksha1996** [ballerinalang/composer#2602]
**SQL connector close element added to the diagram and the following error appeared in the developer console.** 

```
bundle.js:51 Error while completing the drop event. TypeError: Cannot read property 'setVariableName' of undefined
    at VariableDefinitionStatement.value (http://localhost:9091/dist/bundle.js:65:213270)
    at http://localhost:9091/dist/bundle.js:34:59688
    at arrayEach (http://localhost:9091/dist/bundle.js:1:1234)
    at Function.forEach (http://localhost:9091/dist/bundle.js:1:49746)
    at Function.value (http://localhost:9091/dist/bundle.js:34:59128)
    at VariableDefinitionStatement.value (http://localhost:9091/dist/bundle.js:65:215393)
    at ConnectorAction.value (http://localhost:9091/dist/bundle.js:29:98268)
    at ConnectorAction.value (http://localhost:9091/dist/bundle.js:65:144743)
    at HTMLDivElement.<anonymous> (http://localhost:9091/dist/bundle.js:65:1925848)
    at e.(anonymous function).(anonymous function)._trigger (http://localhost:9091/dist/bundle.js:48:7831)

bundle.js:65 Uncaught TypeError: Cannot read property 'getChildren' of undefined
    at VariableDefinitionStatement.value (bundle.js:65)
    at VariableDefinitionStatement.value (bundle.js:65)
    at VariableDefinitionStatementDimensionCalculatorVisitor.value (bundle.js:65)
    at DimensionCalculatorVisitor.value (bundle.js:65)
    at VariableDefinitionStatement.value (bundle.js:29)
    at bundle.js:29
    at arrayEach (bundle.js:1)
    at Function.forEach (bundle.js:1)
    at ConnectorAction.value (bundle.js:29)
    at bundle.js:29
```

**Comment by NipunaMarcus** [comment]
This issue has been fixed with the PR https://github.com/ballerinalang/composer/pull/2627, hence closing this issue.
