### ISSUE TITLE
Incorrect error message when adding a query/path param incorrectly

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2618]
Release 0.91

Add the query param from the design view as follows.
@http:QueryParam{value:"bar"}

**Issue**
1. Error message is not meaningful
![ueryparams](https://user-images.githubusercontent.com/1845370/28523126-96219a66-7098-11e7-8f01-5468a400f02b.png)

Following error is logged in the backend
```
line 1:25 token recognition error at: '\'
line 1:7 token recognition error at: '\'
2017-07-24 17:46:47,061 ERROR - Error while parsing BLang fragment.
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at org.ballerinalang.util.parser.antlr4.BLangAntlr4Listener.exitParameter(BLangAntlr4Listener.java:2454)
	at org.ballerinalang.util.parser.BallerinaParser$ParameterContext.exitRule(BallerinaParser.java:7843)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.ballerinalang.util.parser.BallerinaParser.compilationUnit(BallerinaParser.java:330)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.getJsonModel(BLangFragmentParser.java:126)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:55)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler$$Lambda$28/1452002049.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Expected**
A meaningful error message should be given

**Comment by NipunaMarcus** [comment]
This is no longer reproduce-able as this issue is fixed hence closing this issue. Please reopen this ticket if this occur again.
