### ISSUE TITLE
Intermittent Java error logged

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#2914]
Pack - 23/08/2017

```
ERROR - Error while parsing BLang fragment.
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at org.ballerinalang.model.builder.BLangModelBuilder.createBinaryExpr(BLangModelBuilder.java:706)
	at org.ballerinalang.util.parser.antlr4.BLangAntlr4Listener.createBinaryExpr(BLangAntlr4Listener.java:2950)
	at org.ballerinalang.util.parser.antlr4.BLangAntlr4Listener.exitBinaryAddSubExpression(BLangAntlr4Listener.java:2383)
	at org.ballerinalang.util.parser.BallerinaParser$BinaryAddSubExpressionContext.exitRule(BallerinaParser.java:7357)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.ballerinalang.util.parser.BallerinaParser.compilationUnit(BallerinaParser.java:335)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.getJsonModel(BLangFragmentParser.java:139)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:55)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler$$Lambda$30/796569511.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by NatashaWso2** [comment]
This cannot be reproduced in the latest master, hence this issue can be closed.
