### ISSUE TITLE
Var is not supported in structs

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3158]
Pack - 0.93 (25/09)

Var is not available as a data type in structs. When try to add it manually, the following error will be thrown.

```
2017-09-25 11:23:08,718 ERROR - Error while parsing BLang fragment.
java.lang.IllegalStateException: Expression stack cannot be empty in processing an ExpressionList
	at org.ballerinalang.model.builder.BLangModelBuilder.addExprToList(BLangModelBuilder.java:2006)
	at org.ballerinalang.model.builder.BLangModelBuilder.endVarRefList(BLangModelBuilder.java:653)
	at org.ballerinalang.util.parser.antlr4.BLangAntlr4Listener.exitVariableReferenceList(BLangAntlr4Listener.java:1426)
	at org.ballerinalang.util.parser.BallerinaParser$VariableReferenceListContext.exitRule(BallerinaParser.java:4289)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.ballerinalang.util.parser.BallerinaParser.compilationUnit(BallerinaParser.java:335)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.getJsonModel(BLangFragmentParser.java:139)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:55)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler$$Lambda$29/1111747601.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by NatashaWso2** [comment]
This is restricted by design you can only field definitions that are starting from type names and not from 'var' to a struct.
https://github.com/ballerinalang/website/blob/master/docs/user-guide/0.9/grammar/BallerinaParser.g4#L491
