### ISSUE TITLE
NullPointerException when a xml type temp variable is tried to be added

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3643]
NullPointerException when a xml type temp variable is tried to be added in transform

```
Oct 12, 2017 6:58:38 PM org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser parseFragment
SEVERE: Error while parsing BLang fragment.
java.lang.NullPointerException
        at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.getJsonModel(BLangFragmentParser.java:129)
        at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:46)
        at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:141)
        at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
        at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
        at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
        at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by keizer619** [comment]
Following PR [1] will fix this issue.
[1] https://github.com/ballerinalang/composer/pull/3805
