### ISSUE TITLE
Stack-overflow error when the swagger is edited

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/composer#3652]
*Steps*

1. Create a service.
2. Go to swagger view.
3. Manually change an element in the swagger.
4. Click on design view

**Issue:** Following StackOverflow error is thrown.

```
Oct 12, 2017 7:19:01 PM org.wso2.msf4j.internal.MSF4JMessageProcessor handleThrowable
WARNING: Unmapped exception
java.lang.StackOverflowError
	at org.wso2.ballerinalang.compiler.parser.BLangPackageBuilder.addImportPackageDeclaration(BLangPackageBuilder.java:859)
	at org.wso2.ballerinalang.compiler.parser.BLangParserListener.exitImportDeclaration(BLangParserListener.java:140)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser$ImportDeclarationContext.exitRule(BallerinaParser.java:519)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:430)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:646)
	at org.wso2.ballerinalang.compiler.parser.antlr4.BallerinaParser.compilationUnit(BallerinaParser.java:336)
	at org.wso2.ballerinalang.compiler.parser.Parser.generateCompilationUnit(Parser.java:96)
	at org.wso2.ballerinalang.compiler.parser.Parser.lambda$parse$7(Parser.java:75)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.parser.Parser.parse(Parser.java:75)
	at org.wso2.ballerinalang.compiler.PackageLoader.sourceCompile(PackageLoader.java:161)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackage(PackageLoader.java:147)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageNode(PackageLoader.java:125)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:252)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:72)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$visit$8(SymbolEnter.java:177)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:177)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:129)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:150)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackage(PackageLoader.java:148)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageNode(PackageLoader.java:125)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:252)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:72)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$visit$8(SymbolEnter.java:177)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:177)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:129)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:150)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackage(PackageLoader.java:148)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageNode(PackageLoader.java:125)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:252)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:72)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$visit$8(SymbolEnter.java:177)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:177)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:129)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:150)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackage(PackageLoader.java:148)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageNode(PackageLoader.java:125)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:252)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:72)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$visit$8(SymbolEnter.java:177)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:177)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:129)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:150)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackage(PackageLoader.java:148)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageNode(PackageLoader.java:125)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:252)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:72)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$visit$8(SymbolEnter.java:177)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:177)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:129)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.definePackage(SymbolEnter.java:150)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackage(PackageLoader.java:148)
	at org.wso2.ballerinalang.compiler.PackageLoader.loadPackageNode(PackageLoader.java:125)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.visit(SymbolEnter.java:252)
	at org.wso2.ballerinalang.compiler.tree.BLangImportPackage.accept(BLangImportPackage.java:72)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.defineNode(SymbolEnter.java:157)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolEnter.lambda$visit$8(SymbolEnter.java:177)
	at java.util.ArrayList.forEach(ArrayList.java:1249)

```

**Comment by hemikak** [comment]
@yasassri , this may be relevant to a specific swagger definition. Will you be able to attach it ?

**Comment by maheeka** [comment]
This issue cannot be reproduced. Could be specific to a particular configuration. Please reopen if this can be reproduced. 

Handled all exceptions in swagger api that will stop stacktrace from printing with https://github.com/ballerinalang/composer/pull/4595/commits/6aed16bb6d8786050a1570162380443ef927ef9d
