### ISSUE TITLE
ArrayIndexOutOfBounce exception when assignment element is used

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3658]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Steps
1. Add assignment element
2. Clear the content entirely -> element will dissapear
3. Readd the assignment element

Actual behaviour
Composer freezes as given in the attached image. Following exception occurs in the backend
```
Oct 12, 2017 7:55:24 PM org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser parseFragment
SEVERE: Error while parsing BLang fragment.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.google.gson.JsonArray.get(JsonArray.java:183)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.getJsonNodeForFragment(BLangFragmentParser.java:97)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:52)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:141)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
![com_0 94_issue](https://user-images.githubusercontent.com/15624590/31501393-c4cdd608-af87-11e7-8cd7-e7d6be49903b.png)

**Comment by nadeeshaan** [comment]
This is fixed in the latest head 682b93229d88e7de74c334a08d1b1b49a358b8da
