### ISSUE TITLE
Cannot change the return statement to a named return from the design view

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/composer#3697]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Steps**
1. Add a function with named returns
2. Drop in a return expression
3. Change the syntax from `return m;` to `return;` by erasing from right hand side till n of return, then enter ; and press enter

The return expression dissapears with the following error log in the back end
```
Oct 13, 2017 11:47:42 AM org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser parseFragment
SEVERE: Error while parsing BLang fragment.
java.lang.NullPointerException
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.getJsonModel(BLangFragmentParser.java:129)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:46)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by sumuditha-viraj** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/3739

When user provides an incorrect content an alert will be pop up and provided invalid content will be discarded. Statement box will be reverted back to the old state.

![image](https://user-images.githubusercontent.com/6814264/31575083-01a604ae-b0fc-11e7-90af-bfb3368a08c2.png)
