### ISSUE TITLE
Cannot add new variables to the source/target unless they have default values

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#3781]
Try to add a new variable without a default value (except string).

**Issue**
You cannot add and the following error is logged
```
Oct 16, 2017 9:00:30 PM org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser parseFragment
SEVERE: Error while parsing BLang fragment.
java.lang.Exception: Incorrect format of the generated JSON
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:55)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:142)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler$$Lambda$30/23428994.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by keizer619** [comment]
This is same as following issue [1], you need to define default value. Printing following error is a bug now its being validated and pop up a error message

[1] https://github.com/ballerinalang/composer/issues/3986
