### ISSUE TITLE
Cannot import nested json in Structs

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4264]
**Steps**
1. Try importing the following json in structs
```
{
	"id": "0001",
	"type": "donut",
	"name": "Cake",
	"image":
		{
			"url": "images/0001.jpg",
			"width": 200,
			"height": 200
		},
	"thumbnail":
		{
			"url": "images/thumbnails/0001.jpg",
			"width": 32,
			"height": 32
		}
}
```

**Issue**
1. Only the first field (id) will be updated in the struct
2. No error messages are displayed to the user from the composer
3. The following java error will be logged in the console
```
Oct 29, 2017 10:31:16 AM org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser parseFragment
SEVERE: Error while parsing BLang fragment.
java.lang.Exception: Incorrect format of the generated JSON
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:55)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:104)
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler$$Lambda$30/2053651520.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
![34](https://user-images.githubusercontent.com/1845370/32140841-f1efce4c-bc94-11e7-8786-f96724defade.png)

**Comment by dilinisg** [comment]
Cannot add a nested json from the struct construct as well. But no error is shown to the user
eg:
type: json
default value: {"e":"2", "w": {"q":"w"}}

**Comment by NipunaMarcus** [comment]
Related task #4287

**Comment by dilinisg** [comment]
Observed in the new pack - 0.95 SNAPSHOT(4/11/2017) as well
