### ISSUE TITLE
Cannot import a valid json in structs

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4265]
1. Try to import the following json
```
{
	"id": "0001",
	"type": "donut",
	"name": "Cake",
	"image": "qq",
	"url": "images/0001.jpg",
	"width": "200",
	"height": "200",
	"thumbnail": "w",
	"url34444": "images/thumbnails/0001.jpg",
	"width9": "200",
	"height9": "200",
	"id2": "0001",
	"type2": "donut",
	"name2": "Cake",
	"image2": "qq",
	"url2": "images/0001.jpg",
	"width2": "200",
	"height2": "200",
	"thumbnail2": "w",
	"url255": "images/thumbnails/0001.jpg",
	"width255": "200",
	"height255": "200",
	"id3": "0001",
	"type3": "donut",
	"name3": "Cake",
	"image3": "qq",
	"url3": "images/0001.jpg",
	"width3": "200",
	"height3": "200",
	"thumbnail3": "w",
	"url355": "images/thumbnails/0001.jpg",
	"width355": "200",
	"height355": "200",
	"id4": "0001",
	"type34": "donut",
	"name34": "Cake",
	"image34": "qq",
	"url34": "images/0001.jpg",
	"width34": "200",
	"height34": "200",
	"thumbnail34": "w",
	"url3455": "images/thumbnails/0001.jpg",
	"width3455": "200",
	"height3455": "200",
	"id45": "0001",
	"type345": "donut",
	"name345": "Cake",
	"image345": "qq",
	"url345": "images/0001.jpg",
	"width345": "200",
	"height345": "200",
	"thumbnail345": "w",
	"url354": "images/thumbnails/0001.jpg",
	"width34566": "200",
	"height34665": "200",
	"id46": "0001",
	"type346": "donut",
	"name346": "Cake",
	"image346": "qq",
	"url346": "images/0001.jpg",
	"width346": "200",
	"height346": "200",
	"thumbnail346": "w",
	"url34666": "images/thumbnails/0001.jpg",
	"width34666": "200",
	"height34666": "200",
	"id47": "0001",
	"type347": "donut",
	"name347": "Cake",
	"image347": "qq",
	"url347": "images/0001.jpg",
	"width347": "200",
	"height347": "200",
	"thumbnail347": "w",
	"url34667": "images/thumbnails/0001.jpg",
	"width34766": "200",
	"height34766": "200"
}
```

**Issue**
1. No error message from the composer
2. The following error in the console
```
Oct 29, 2017 10:51:22 AM org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser parseFragment
SEVERE: Error while parsing BLang fragment.
java.lang.Exception: Incorrect format of the generated JSON
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:55)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:104)
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler$$Lambda$30/2053651520.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by NipunaMarcus** [comment]
Related Task  #4287
