### ISSUE TITLE
Does not validate adding a json with null/empty key

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/composer#4315]
1. Add a json string as shown in the screen shot
2. Click on Import
![45](https://user-images.githubusercontent.com/1845370/32217743-f57fddca-be4e-11e7-8a5b-330e4f987346.png)

**Issue**
No error message shown to the user. But, following is logged in the back-end
```
Oct 31, 2017 3:21:47 PM org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser parseFragment
SEVERE: Error while parsing BLang fragment.
java.lang.Exception: Incorrect format of the generated JSON
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFragmentParser.parseFragment(BLangFragmentParser.java:55)
	at org.ballerinalang.composer.service.workspace.rest.datamodel.BLangFileRestService.getBallerinaJsonDataModelGivenFragment(BLangFileRestService.java:104)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:130)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.receive(MSF4JMessageProcessor.java:72)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler.lambda$publishToWorkerPool$12(WorkerPoolDispatchingSourceHandler.java:125)
	at org.wso2.carbon.transport.http.netty.listener.WorkerPoolDispatchingSourceHandler$$Lambda$30/476383112.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by NipunaMarcus** [comment]
Related Task #4287
