### ISSUE TITLE
Wrong NodeJS version in the README file

### ISSUE THREAD

**Issue by chanikag** [ballerinalang/composer#4586]
The readme file in [1] says the NodeJS  version is 6.x.x. I installed version 6 in ubuntu and tried to build the composer project. But I ended up with the following error. As a solution had to install the NodeJS version to 8 as in [2]

/media/chanika/data/git/ballerina/composer/modules/web/webpack.config.js:11
let exportConfig = {};
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireConfig (/media/chanika/data/git/ballerina/composer/modules/web/node_modules/webpack/bin/convert-argv.js:96:18)
    at /media/chanika/data/git/ballerina/composer/modules/web/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

[1] https://github.com/ballerinalang/composer/blob/master/README.md
[2] https://nodejs.org/en/download/package-manager/

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerinalang/composer/pull/4604
